### ISSUE TITLE
Improve resource association

### ISSUE THREAD

**Issue by barkbay** [elastic/elasticsearch-k8s-metrics-adapter#11]
For now metrics are only associated with `Pod` resources: https://github.com/elastic/elasticsearch-k8s-metrics-adapter/blob/39a36d92afb8cb0edc754c110fc5a7949fe9550f/pkg/client/elasticsearch/discovery.go#L195-L200
Also namespace and Pod's name fields are hardcoded in the [Elasticsearch query](https://github.com/elastic/elasticsearch-k8s-metrics-adapter/blob/39a36d92afb8cb0edc754c110fc5a7949fe9550f/pkg/client/elasticsearch/client.go#L49):

```json
{
	"query": {
		"bool": {
			"must": [{
				"exists": {
					"field": "%s"
				}
			}, {
				"match": {
					"kubernetes.namespace": "%s" -- here
				}
			}, {
				"match": {
					"kubernetes.pod.name": "%s" -- here
				}
			}]
		}
	}
}
```

Not all metrics make sense in the context of Pods. For example it does not make sense to expose `system.memory.free` as it is not possible to associate this metric to a specific Pod. The first approach so far has been to filter on the metric name and assume documents also have the  `kubernetes.namespace` and `kubernetes.pod.name` fields:

```yaml
metricSets:
  - indices: [ 'metricbeat-*' ]
    fields:
      - patterns: [ '^prometheus\.metrics\.' , '^kibana\.stats\.'  ] # only serve metrics with namespace and pod name
```

We then assume that we get that kind of document from Elasticsearch:

```json
{
  "_index": "metricbeat-7.14.0-2021.09.21-000001",
  "_type": "_doc",
  "_id": "10V6DXwBJBC0gYXF1JYC",
  "fields": {
     "prometheus.metrics.go_memstats_frees_total": [
      123418991
    ],
   [ ... other metrics starting with prometheus.metrics* ...]
   "kubernetes.pod.name": [
      "kube-dns-b4f5c58c7-47twh"
    ],
   "kubernetes.namespace": [
      "kube-system"
    ],
    "@timestamp": [
      "2021-09-22T12:28:44.448Z"
    ]
  }
}
```

We may want to improve this association mechanism, for example by allowing other resources to be associated with a given metric. Users may also want to use other fields than `kubernetes.namespace` or `kubernetes.pod.name` to query for a given metric.

See [here](https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/config.md#association) how associations are managed with the Prometheus adapter.

**Comment by Trojan295** [comment]
I would love to see this! I have a use-case, where I would like to scale based on request count coming to an Ingress:
```
    metrics:
      - type: Object
        object:
          describedObject:
            apiVersion: networking.k8s.io/v1
            kind: Ingress
            name: http-api
          metric:
            name: nginx_ingress_controller_requests
          target:
            value: "600"
            type: AverageValue
```
