### ISSUE TITLE
Allow metric name customization

### ISSUE THREAD

**Issue by barkbay** [elastic/elasticsearch-k8s-metrics-adapter#4]
It should be possible to change the name of the metrics as they are exposed to Kubernetes. It could be useful when some metrics are available on different servers but share the same name. By using the name, the user is then able to select which metrics server should be used.

For example:

```yaml
metricServers:
  - name: server1
    type: elasticsearch
    rename:
      matches: "^(.*)$"
      as: "${1}@server1"
```

All the metrics on `server1` can be accessed with the postfix  `@server1`

Inspired from https://github.com/kubernetes-sigs/prometheus-adapter/blob/master/docs/config.md#naming
